# vim: set ft=make:

EM_PCHDIR:=$(OBJDIR)$(if $(CONFIG),/$(CONFIG))/.em
EM_HDR:=$(EM_PCHDIR)/$(NAME).h
PCH:=$(EM_HDR)$(PCHEXT)
PKG:=$(LIBDIR)/pkgconfig/$(NAME).pc

$(EM_HDR):EM_SRCS:=$(patsubst $(INCDIR)/%,%,$(SRCS))
$(PCH):EM_PKGS:=$(strip $(PKGS) $(foreach d,$(DEPS),$(EmLibraryPkgs.$d)))
$(PCH):EM_FLAGS:=$(FLAGS)
$(PKG):EM_NAME:=$(NAME)
$(PKG):EM_INCLUDEDIR:=$(EM_PCHDIR)/.em

# Create common header for SRCS
$(EM_HDR):always $$(@D)/.f
	@$(if $(VERBOSE),echo "Checking $@")
	$(file >$@.new) $(foreach i,$(EM_SRCS),$(file >>$@.new,#include <$i>))
	@$(call em_move_ne,$@.new,$@)

# Header compilation parameters
$(EM_HDR).cmd:always $(foreach d,$(DEPS),$(EmLibraryPkgDeps.$d)) $$(@D)/.f
	@$(if $(VERBOSE),echo "Checking $@")
	@$(call em_write_ne,$@,$(strip $(call em_compile,.h) $(EM_FLAGS) $(if $(EM_PKGS),$(shell $(PKG_CONFIG) --cflags $(EM_PKGS))))) 

$(PCH):$(EM_HDR) $(EM_HDR).cmd $(foreach d,$(DEPS),$(EmLibrarySrcDeps.$d)) $$(@D)/.f
	@echo "Compiling$(if $(WANT_PIC), PIC) $<"
	$(if $(VERBOSE),,@)$(strip $(call em_compile,.h) $(EM_FLAGS) $(if $(EM_PKGS),$(shell $(PKG_CONFIG) --cflags $(EM_PKGS))) $<)

# Include dependencies generated by compiler
-include $(EM_HDR)$(DEPEXT)

# Create fake install rules so make doesn't complain
EM_NAME:=$(NAME)
include $(MAKEDIR)/platform/install.make

ifneq ($(WANT_TARGET),)
 $(NAME):$(PCH)
 .PHONY:$(NAME)
endif

EM_PCH_SED:=$(EM_PCHDIR)/$(NAME).pc.sed
$(PKG):EM_PCH_SED:=$(EM_PCH_SED)

$(EM_PCH_SED):always $$(@D)/.f
	@$(if $(VERBOSE),echo "Checking $@")
	@echo 's|@PCHDIR@|$(EM_PCHDIR)|' > $@.new
	@echo 's|@INCLUDE@|$(EM_NAME).h|' >> $@.new
	@$(call em_move_ne,$@.new,$@)

$(PKG):$(MAKEDIR)/platform/pch.pc.in $(EM_PCH_SED) $(EM_PKG_BUILDDIRS_SED) $$(@D)/.f
	$(if $(VERBOSE),,@)sed -f $(EM_PCH_SED) -f $(EM_PKG_BUILDDIRS_SED) $< > $@ 

EmLibraryDeps.$(NAME).pch:=
ifeq ($(WANT_PCH),)
EmLibraryPkgs.$(NAME).pch:=
EmLibraryPkgDeps.$(NAME).pch:=
EmLibrarySrcDeps.$(NAME).pch:=
else
EmLibraryPkgs.$(NAME).pch:=$(PKG)
EmLibraryPkgDeps.$(NAME).pch:=$(PKG) $(foreach d,$(DEPS),$(EmLibraryPkgDeps.$d)) 
EmLibrarySrcDeps.$(NAME).pch:=$(PCH)
endif

EmLibraryDeps.$(NAME):=$(EmLibraryDeps.$(NAME).pch)
EmLibraryPkgs.$(NAME):=$(EmLibraryPkgs.$(NAME).pch)
EmLibraryPkgDeps.$(NAME):=$(EmLibraryPkgDeps.$(NAME).pch)
EmLibrarySrcDeps.$(NAME):=$(EmLibrarySrcDeps.$(NAME).pch)

EM_HDR:=
EM_PCH_SED:=
EM_INCLUDEDIR:=
# end 
