# vim: set ft=make:

# Generate object names
# - src/a.c -> obj/a.c.o
# - EM_OBJPATH
OBJS:=$(patsubst $(SRCDIR)/%,$(EM_OBJPATH)/%$(OBJEXT),$(SRCS))

# rule specific variables
$(OBJS):EM_PKGS:=$(strip $(PKGS) $(foreach d,$(DEPS),$(EmLibraryPkgs.$d)))
$(OBJS):EM_FLAGS:=$(FLAGS)

# Check previous flags
# - EM_FLAGS and EM_FLAGS propagate here too
# - EmLibraryPkgDeps must be built before
# - stem $* is source extension (e.g. .cpp)
$(EM_OBJPATH)/.em/$(EM_NAME)%.cmd:always $(foreach d,$(DEPS),$(EmLibraryPkgDeps.$d)) $$(@D)/.f
	@$(if $(VERBOSE),echo "Checking $@")
	@$(call em_write_ne,$@,$(strip $(call em_compile,$*) $(EM_FLAGS) $(if $(EM_PKGS),$(shell $(PKG_CONFIG) --cflags $(EM_PKGS)))))

# Compile (+ generate *.d)
# - rule only for OBJS
# - stem is source name in SRCDIR
$(OBJS):$(EM_OBJPATH)/%$(OBJEXT):$(SRCDIR)/% $(EM_OBJPATH)/.em/$(EM_NAME)$$(suffix $$*).cmd $(foreach d,$(DEPS),$(EmLibrarySrcDeps.$d)) $$(@D)/.f
	@echo "Compiling$(if $(WANT_PIC), PIC) $<"
	$(if $(VERBOSE),,@)$(strip $(call em_compile,$(suffix $*)) $(EM_FLAGS) $(if $(EM_PKGS),$(shell $(PKG_CONFIG) --cflags $(EM_PKGS))) $<)

# Include dependencies generated by compiler
# - obj/a.c.o -> obj/a.c.d
-include $(patsubst %$(OBJEXT),%$(DEPEXT),$(OBJS))

# reset temporaries
EM_NAME:=
EM_OBJPATH:=
