# vim: set ft=make:

# Generate object names
# - src/a.c -> obj/a.c.o
# - EM_OBJPATH
OBJS:=$(patsubst $(SRCDIR)/%,$(EM_OBJPATH)/%$(OBJEXT),$(SRCS))

# Store flags in rule specific variable
# - add pkg-config --cflags
$(OBJS):EM_FLAGS:=$(FLAGS)$(if $(PKGS), $(shell $(PKG_CONFIG) --cflags $(PKGS)))

# Check previous flags
# - EM_FLAGS propagate here too
$(EM_OBJPATH)/$(EM_NAME).%.cmd:always $$(@D)/.f
	@$(if $(VERBOSE),echo "Checking $@")
	@$(call UpdateIfNotEqual,$@,$(Compile.$*) $(EM_FLAGS))

# Compile (+ generate *.d)
# - rule only for OBJS
$(OBJS):$(EM_OBJPATH)/%$(OBJEXT):$(SRCDIR)/% $(EM_OBJPATH)/$(EM_NAME)$$(suffix $$*).cmd $$(@D)/.f
	@echo "Compiling$(if $(WANT_PIC), PIC) $<"
	$(if $(VERBOSE),,@)$(Compile$(suffix $*)) $(EM_FLAGS) $<

# Include dependencies generated by compiler
# - obj/a.c.o -> obj/a.c.d
-include $(patsubst %$(OBJEXT),%$(DEPEXT),$(OBJS))

# reset temporaries
EM_NAME:=
EM_OBJPATH:=
# end
